### Obtener todos los usuarios
GET http://localhost:3000/users

### Obtener usuario por ID
GET http://localhost:3000/users/68c0efcde8ee7c282b4907c0

### Crear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Juan Perez",
  "email": "juan.perez2@email.com"
}

### Actualizar usuario
PUT http://localhost:3000/users/68c0f1621738a2c237d98371
Content-Type: application/json

{
  "name": "Juan Actualizado",
  "email": "juan.actualizado@email.com"
}

### Eliminar usuario
DELETE http://localhost:3000/users/68c0f1621738a2c237d98371