### Obtener todos los usuarios
GET http://localhost:3000/users

### Obtener usuario por ID
GET http://localhost:3000/users/1

### Crear usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Juan Postg2ress 2",
  "email": "juan.perez22s22@email.com"
}

### Actualizar usuario
PUT http://localhost:3000/users/68bfbd4eb4a2b228ffa14dfe
Content-Type: application/json

{
  "name": "Juan Actualizado",
  "email": "juan.actualizado@email.com"
}

### Eliminar usuario
DELETE http://localhost:3000/users/2