### Obtener todos los usuarios
GET http://localhost:3000/usuarios

### Obtener usuario por ID
GET http://localhost:3000/usuarios/1

### Crear usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "email": "juan.perez@email.com"
}

### Actualizar usuario
PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
  "nombre": "Juan Actualizado",
  "email": "juan.actualizado@email.com"
}

### Eliminar usuario
DELETE http://localhost:3000/usuarios/2